# **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [5]:
a[:2*1].reshape(2, 1)

array([[12],
       [13]])

In [6]:
a[:2*2].reshape(2, 2)

array([[12, 13],
       [14, 15]])

In [9]:
for i in range(1, 6):
    print(a[:2*i].reshape(2, i))

[[12]
 [13]]
[[12 13]
 [14 15]]
[[12 13 14]
 [15 16 17]]
[[12 13 14 15]
 [16 17 18 19]]
[[12 13 14 15 16]
 [17 18 19 20 21]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [17]:
a[:12].reshape(2, -1)
a[:10].reshape(2, -1)
a[:8].reshape(2, -1)
a[:12].reshape(-1, 2)
a[:10].reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нельзя, поскольку элемент одномерного массива не массив. И для итерации по ним нужно два параметра `i` и `j`.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [19]:
b = np.random.randn(3, 4)
b

array([[ 0.33540713,  0.92254766,  0.05307247,  0.46439529],
       [-1.06001916,  0.4443525 , -1.1438011 ,  0.58370285],
       [ 1.40497119,  1.02698878, -0.17424217, -0.38588226]])

In [21]:
c = b.flatten()
c

array([ 0.33540713,  0.92254766,  0.05307247,  0.46439529, -1.06001916,
        0.4443525 , -1.1438011 ,  0.58370285,  1.40497119,  1.02698878,
       -0.17424217, -0.38588226])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [25]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [31]:
b = np.arange(20, 1, -2).reshape(1, -1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

а - одномерным, б - двумерный

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [41]:
# Вертикально, то есть дописать один массив под другой
# Если у нас два двумерных массива, то при их объединении
# size будет 10, примем количество столбцов - 2, тогда
# количество строк будет 10 / 2 = 5. Поскольку строки
# одного массива больше или меньше на одну, то пусть для
# первого массива количество строк 2, а для второго 3.
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
print(c, c.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [49]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [51]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

> Какой размер имеет матрица B?

(строк_A, столбцов_At)

In [53]:
# обратную матрицу можно вычислить для матрицы,
# определитель которой не равен 0. Определитель можно
# посчитать для квадратной матрицы.
d = np.linalg.det(B)
d

0.0

In [55]:
# нельзя вычислить обратную матрицы

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [64]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [67]:
a = np.random.randint(0, 16, 16)
a

array([ 1,  7, 11, 13,  5,  1, 15, 11,  4,  0, 11,  9,  5, 12, 11,  8])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.